### ISSUE TITLE
TileDB-VCF Functionalities

### ISSUE THREAD

**Issue by aardes** [TileDB-Inc/TileDB-VCF#386]
Dear,

I recently start looking into TileDB-VCF and testing it, I have some questions:

1- Does Tiledb-VCF have the ability to calculate the unique list of Chromosomal positions across all the samples or we should implement this functionality with for example Python API?

2- If I add the same sample as I stored previously in the database, data is added to the previous sample, and records will be doubled. As I checked the --no-duplicates should be defined at the time of the creation of the dataset and I assume this prevents a sample or a duplicate record from being added to the dataset. But I want to know can I use the timestamp to always query the latest version of each record?

3- The timestamp is an autogenerated value, or do I need to define it beforehand?

Sorry for the questions, and tanks in advance.

Kind Regards
Amin

**Comment by gspowley** [comment]
Sorry that your questions went unanswered for so long @aardes.

> 1- Does Tiledb-VCF have the ability to calculate the unique list of Chromosomal positions across all the samples or we should implement this functionality with for example Python API?

TileDB-VCF versions >= 0.18.0 create an allele count array that contains the positions for all variants across all samples. If you are interested, we can share more information on using the allele count array for this purpose.

> 2- If I add the same sample as I stored previously in the database, data is added to the previous sample, and records will be doubled. As I checked the --no-duplicates should be defined at the time of the creation of the dataset and I assume this prevents a sample or a duplicate record from being added to the dataset. But I want to know can I use the timestamp to always query the latest version of each record?

Yes, you can open the dataset with a timestamp to control which records are returned by the query.

> 3- The timestamp is an autogenerated value, or do I need to define it beforehand?

The timestamps are auto-generated, based on the time the data is ingested.

I'll close this issue since it has been inactive. Please reopen or open a new issue if you have any more questions.
