### ISSUE TITLE
How to compile with conda?

### ISSUE THREAD

**Issue by Hoeze** [TileDB-Inc/TileDB-VCF#47]
Hi, could you please provide some information how to compile this package within a conda-environment?
I guess I have to somehow build libtiledb with `cmake -DFORCE_EXTERNAL_HTSLIB=OFF`?

**Comment by ihnorton** [comment]
Hi @Hoeze, are you able to build with these steps?: https://docs.tiledb.com/developer/tiledbvcf/installation/python

We will add support for building against libtiledb and htslib from conda (see https://github.com/TileDB-Inc/TileDB-VCF/pull/48) -- in order to facilitate making a conda package too. However, I need to update the package for compatibility with arrow changes (some tests currently fail) -- will do as soon as possible.

**Comment by Hoeze** [comment]
Hi @ihnorton, thanks for your answer.

Using your instructions did not work because I was missing some header files in conda (where do I get header files for e.g. zlib?).
Compiling against the system is not possible for the same reason.

Yesterday I was able to compile against conda's htslib:
1) first compile libtiledbvcf using `cmake -DFORCE_EXTERNAL_HTSLIB=OFF <libtiledbvcf_folder> && make` 
2) `python setup.py install` the python package.
However, I did not test it yet, I only tried the import.

**Comment by ihnorton** [comment]
Hi @Hoeze, as soon as the next arrow release is available, I will submit a conda recipe for this package -- the release process is happening now. TileDB-VCF has some test failures when building against arrow 0.15, and these are fixed upstream in arrow 0.16. (I haven't been able to find a workaround for this issue on our side yet, so I'm going to defer to the imminent release for a fix).

**Comment by Hoeze** [comment]
Thanks a lot @ihnorton!

**Comment by ihnorton** [comment]
Hi @Hoeze, sorry about the delay here. I've uploaded an initial conda package for linux.
- package: https://anaconda.org/tiledb/tiledbvcf-py
- you can see the build recipe: https://github.com/TileDB-Inc/staged-recipes/tree/tiledb/tiledb-vcf
- install with:
    `conda install -c conda-forge -c bioconda -c tiledb tiledbvcf-py`

If you want to build in your own environment w/ tiledb and htslib installed, use `python setup.py install --libtiledbvcf=${CONDA_PREFIX}`

I will work on submitting this to bioconda soon, that seems like a better channel than conda-forge due to the scope and htslib dependency.

**Comment by ihnorton** [comment]
@aaronwolen was this fixed by #98?

**Comment by aaronwolen** [comment]
Actually, no. I just tried following the python install directions inside a fresh ubuntu container and it went belly up linking the aws sdk. It's some kind of issue w/ conda because the CLI builds fine w/ conda deactivated. 

I'll investigate but let me know if you have any suggestions, @ihnorton.

**Comment by gspowley** [comment]
Closing this issue since it has been inactive. Please reopen if there is still an issue.
