### ISSUE TITLE
Problems installing on Ubuntu 20.04

### ISSUE THREAD

**Issue by etnite** [TileDB-Inc/TileDB-VCF#780]
I recently tried installing the TileDB-VCF CLI via conda on a system running Ubuntu 20.04. It appears that TileDB v2.16 gets installed, and htslib gets downgraded to v1.16.

The installation appears to be successful, but when I try running `tiledbvcf version` I get:

`tiledbvcf: error while loading shared libraries: libicudata.so.70: cannot open shared object file: No such file or directory`

I know that Ubuntu 20.04 installs libicu version 66 while Ubuntu 22.04 installs version 70 - is there an older version of tiledbvcf I can specify when installing with Conda that will still be compatible with Ubuntu 20.04? I think this system I'm working on will likely be running Ubuntu 20.04 until near the end of its support window.

Thank you

**Comment by etnite** [comment]
Thank you @jdblischak. Following along with what you wrote, it looks like I was able to get TileDB-VCF working. I think the main issue on my end was that I was attempting to install into a pre-existing conda environment, containing the Octopus variant caller and its dependencies. Trying again creating a fresh env. as you did seemed to fix the issue.

I noticed that the documentation on the TileDB site also has the Bioconda channel listed in the conda install prompt:

`conda install -c conda-forge -c bioconda -c tiledb libtiledbvcf`

Whereas your command above has it omitted. I tried creating the environment with and without `-c bioconda` included and it appears that it worked either way.

**Comment by jdblischak** [comment]
> Whereas your command above has it omitted. I tried creating the environment with and without `-c bioconda` included and it appears that it worked either way.

We have created our own conda binaries for htslib. We did this since we sometimes get conda solver errors because htslib is on bioconda, and sometimes bioconda and conda-forge temporarily diverge in their required pinned dependencies.

https://anaconda.org/tiledb/htslib
https://anaconda.org/tiledb/m2w64-htslib

However, if you'd prefer to install htslib from bioconda, it's totally fine (and recommended as long as there are no solver errors) to specify the channels as `-c conda-forge -c bioconda -c tiledb` like you did above.
